server:
  port: 9000
spring:
  application:
    name: leyou-search
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.100.102:9300
  jackson:
    default-property-inclusion: non_null  #属性值为空不返回给前端
  rabbitmq:
    password: guest
    username: guest
    host: 127.0.0.1
    virtual-host: /
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10087/eureka
    registry-fetch-interval-seconds: 5
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    #instance-id: ${spring.application.name}:${server.port}